### ISSUE TITLE
Hide nametags of players behind walls, blocks or structures...

### ISSUE THREAD

**Issue by ga6rielsilva** [Tanguygab/TAB-Additions#28]
![image](https://user-images.githubusercontent.com/62969752/223958494-d2a29043-e4fb-4efa-b372-2b43dcffb269.png)

**Comment by Tanguygab** [comment]
too complex for me, I don't think I'll be able to add that anytime soon

**Comment by Tanguygab** [comment]
I've seen that plugin as well in the past but never got the patience to see how it's done and implement it 🥲

**Comment by ga6rielsilva** [comment]
> I've seen that plugin as well in the past but never got the patience to see how it's done and implement it 🥲

And about the world setting?

**Comment by Tanguygab** [comment]
you can use conditional-nametags to set a condition that checks the world, for example, go in TAB's config.yml, create a new condition:
```yml
conditions:
  nametag:
    conditions:
      - "%world%=world1"
      - "%world%=world2"
      - "%world%=world3"
    type: OR
```
and then go in group.yml and add
```yml
_DEFAULT_:
  nametag-condition: nametag
```
